name: 🐞 Bug Report
description: Create a bug report to help us improve.

body:
  - type: markdown
    attributes:
      value: |
        Before you continue reporting the bug, be sure that you are using supported installation method, see

        - https://github.com/Taxel/PlexTraktSync#installation

        You can find latest version from here:
        - https://github.com/Taxel/PlexTraktSync/tags

  - type: checkboxes
    id: readme
    attributes:
      options:
        - label: I have read the README.md on the project homepage.
          required: true
      
  - type: textarea
    id: description
    attributes:
      label: The problem
      description: A description of what the bug is
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      render: text
      label: Error trace / logs
      description: >
        A complete traceback of the error or content of log file.

        This will be automatically formatted into code, so no need for backticks.

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the behavior
      description: Write the command you used to run it, what you did before and after
    validations:
      required: true


  - type: textarea
    id: inspect
    attributes:
      render: text
      label: Inspect of problematic items
      description: >
        Post here `plextraktsync inspect ID` if needed to understand the problem.

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Is there an existing workaround for this issue? Did you try downgrading? Try finding version that can be used as a workaround.

  - type: dropdown
    id: install-method
    attributes:
      label: Install method
      description: How did you install PlexTraktSync
      options:
        - pipx (Recommended)
        - pip
        - docker-compose
        - git clone
        - zip download
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Run plextraktsync info
      placeholder: eg. 0.15.0
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: eg. 3.7.10
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System and Version
      placeholder: eg. Windows 10, macOS 10.15, Ubuntu 20.04, etc.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure to close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
