contact_links:
  - name: 💬 Discussions
    url: https://github.com/Taxel/PlexTraktSync/discussions/new?category=support
    about: Please use Discussions to ask for community support. Bugs (application crashes, errors) needs to be reported to developers as issues.
blank_issues_enabled: false
