# This workflow will upload a Python Package using Twine when a release is created
# For more information see:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PyPI

on:
  workflow_dispatch: ~
  release:
    types: [published]

env:
  DEFAULT_PYTHON: 3.7

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version variable
      id: vars
      run: |
        if [[ "${GITHUB_REF#refs/heads/}" = "${GITHUB_REF}" ]]; then
          APP_VERSION=${GITHUB_REF#refs/tags/}
        else
          git fetch --tags --unshallow
          APP_VERSION=$(git describe --tags)_${GITHUB_REF#refs/heads/}
        fi
        echo ::set-output name=version::$APP_VERSION

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.DEFAULT_PYTHON }}

    - name: Install dependencies and build
      env:
        APP_VERSION: ${{ steps.vars.outputs.version }}
      run: |
        python -m pip install --upgrade build
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}

# vim:ts=2:sw=2:et
